services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/venv
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/timesheet.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    restart: unless-stopped